# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpotifyCli < Formula
  desc ""
  homepage ""
  version "0.2.0"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zext/spotify-cli/releases/download/v0.2.0/spotify-cli_0.2.0_linux_x86_64.tar.gz"
      sha256 "dd66cca23f1fdefd82a11fdbd778f8e79199366bd50621428a96767540816f11"

      def install
        bin.install "spotify-cli"
      end
    end
  end
end
