# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpotifyCli < Formula
  desc ""
  homepage ""
  version "0.1.1"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zext/spotify-cli/releases/download/v0.1.1/spotify-cli_0.1.1_linux_x86_64.tar.gz"
      sha256 "d5b294b345b9105889d03c138b842270801354dcccf78cd00e3694e41edaa094"

      def install
        bin.install "spotify-cli"
      end
    end
  end
end
